server:
  port: 81
  servlet:
    context-path: /x
spring:
  ## 数据库配置
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/pp?useAffectedRows=true&useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    username: BJ_TEST
  #    password: 123456789
  #    url: jdbc:oracle:thin:@192.168.14.156:1521:orcl
  #    type: com.alibaba.druid.pool.DruidDataSource
  #    driver-class-name: oracle.jdbc.OracleDriver
  ## 方言配置
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    ##database-platform: org.hibernate.dialect.Oracle10gDialect
    ##database-platform: org.hibernate.dialect.Oracle12cDialect
  ## 文件上传大小配置,不限制大小
  servlet:
    multipart:
      maxFileSize: -1
      maxRequestSize: -1
